# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mujoco_data

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class JointData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JointData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJointData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # JointData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JointData
    def JointId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # JointData
    def JointType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # JointData
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JointData
    def Qpos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # JointData
    def QposAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # JointData
    def QposLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # JointData
    def QposIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # JointData
    def Qvel(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # JointData
    def QvelAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # JointData
    def QvelLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # JointData
    def QvelIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def JointDataStart(builder):
    builder.StartObject(5)

def Start(builder):
    JointDataStart(builder)

def JointDataAddJointId(builder, jointId):
    builder.PrependUint32Slot(0, jointId, 0)

def AddJointId(builder, jointId):
    JointDataAddJointId(builder, jointId)

def JointDataAddJointType(builder, jointType):
    builder.PrependUint8Slot(1, jointType, 0)

def AddJointType(builder, jointType):
    JointDataAddJointType(builder, jointType)

def JointDataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    JointDataAddName(builder, name)

def JointDataAddQpos(builder, qpos):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(qpos), 0)

def AddQpos(builder, qpos):
    JointDataAddQpos(builder, qpos)

def JointDataStartQposVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartQposVector(builder, numElems):
    return JointDataStartQposVector(builder, numElems)

def JointDataAddQvel(builder, qvel):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(qvel), 0)

def AddQvel(builder, qvel):
    JointDataAddQvel(builder, qvel)

def JointDataStartQvelVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartQvelVector(builder, numElems):
    return JointDataStartQvelVector(builder, numElems)

def JointDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return JointDataEnd(builder)
