# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mujoco_data

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MujocoDataFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MujocoDataFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMujocoDataFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MujocoDataFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MujocoDataFrame
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MujocoDataFrame
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MujocoDataFrame
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MujocoDataFrame
    def SimTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MujocoDataFrame
    def Joints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from mujoco_data.JointData import JointData
            obj = JointData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MujocoDataFrame
    def JointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MujocoDataFrame
    def JointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # MujocoDataFrame
    def Sensors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from mujoco_data.SensorData import SensorData
            obj = SensorData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MujocoDataFrame
    def SensorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MujocoDataFrame
    def SensorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # MujocoDataFrame
    def Bodies(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from mujoco_data.PoseData import PoseData
            obj = PoseData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MujocoDataFrame
    def BodiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MujocoDataFrame
    def BodiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # MujocoDataFrame
    def IsValid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def MujocoDataFrameStart(builder):
    builder.StartObject(8)

def Start(builder):
    MujocoDataFrameStart(builder)

def MujocoDataFrameAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder, description):
    MujocoDataFrameAddDescription(builder, description)

def MujocoDataFrameAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(1, timestamp, 0)

def AddTimestamp(builder, timestamp):
    MujocoDataFrameAddTimestamp(builder, timestamp)

def MujocoDataFrameAddFrameId(builder, frameId):
    builder.PrependUint64Slot(2, frameId, 0)

def AddFrameId(builder, frameId):
    MujocoDataFrameAddFrameId(builder, frameId)

def MujocoDataFrameAddSimTime(builder, simTime):
    builder.PrependFloat64Slot(3, simTime, 0.0)

def AddSimTime(builder, simTime):
    MujocoDataFrameAddSimTime(builder, simTime)

def MujocoDataFrameAddJoints(builder, joints):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(joints), 0)

def AddJoints(builder, joints):
    MujocoDataFrameAddJoints(builder, joints)

def MujocoDataFrameStartJointsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJointsVector(builder, numElems):
    return MujocoDataFrameStartJointsVector(builder, numElems)

def MujocoDataFrameAddSensors(builder, sensors):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(sensors), 0)

def AddSensors(builder, sensors):
    MujocoDataFrameAddSensors(builder, sensors)

def MujocoDataFrameStartSensorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSensorsVector(builder, numElems):
    return MujocoDataFrameStartSensorsVector(builder, numElems)

def MujocoDataFrameAddBodies(builder, bodies):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(bodies), 0)

def AddBodies(builder, bodies):
    MujocoDataFrameAddBodies(builder, bodies)

def MujocoDataFrameStartBodiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBodiesVector(builder, numElems):
    return MujocoDataFrameStartBodiesVector(builder, numElems)

def MujocoDataFrameAddIsValid(builder, isValid):
    builder.PrependBoolSlot(7, isValid, 1)

def AddIsValid(builder, isValid):
    MujocoDataFrameAddIsValid(builder, isValid)

def MujocoDataFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return MujocoDataFrameEnd(builder)
