# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mujoco_data

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SensorData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SensorData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSensorData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SensorData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SensorData
    def SensorId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # SensorData
    def ValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # SensorData
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorData
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # SensorData
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SensorDataStart(builder):
    builder.StartObject(3)

def Start(builder):
    SensorDataStart(builder)

def SensorDataAddSensorId(builder, sensorId):
    builder.PrependUint32Slot(0, sensorId, 0)

def AddSensorId(builder, sensorId):
    SensorDataAddSensorId(builder, sensorId)

def SensorDataAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)

def AddValues(builder, values):
    SensorDataAddValues(builder, values)

def SensorDataStartValuesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartValuesVector(builder, numElems):
    return SensorDataStartValuesVector(builder, numElems)

def SensorDataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    SensorDataAddName(builder, name)

def SensorDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return SensorDataEnd(builder)
