# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mujoco_data

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ActuatorData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ActuatorData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsActuatorData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ActuatorData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ActuatorData
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ActuatorData
    def ActuatorId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ActuatorData
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ActuatorDataStart(builder):
    builder.StartObject(3)

def Start(builder):
    ActuatorDataStart(builder)

def ActuatorDataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ActuatorDataAddName(builder, name)

def ActuatorDataAddActuatorId(builder, actuatorId):
    builder.PrependUint32Slot(1, actuatorId, 0)

def AddActuatorId(builder, actuatorId):
    ActuatorDataAddActuatorId(builder, actuatorId)

def ActuatorDataAddData(builder, data):
    builder.PrependFloat64Slot(2, data, 0.0)

def AddData(builder, data):
    ActuatorDataAddData(builder, data)

def ActuatorDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return ActuatorDataEnd(builder)
