# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mujoco_data

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ActuatorCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ActuatorCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsActuatorCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ActuatorCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ActuatorCommand
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ActuatorCommand
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ActuatorCommandStart(builder):
    builder.StartObject(2)

def Start(builder):
    ActuatorCommandStart(builder)

def ActuatorCommandAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ActuatorCommandAddName(builder, name)

def ActuatorCommandAddData(builder, data):
    builder.PrependFloat64Slot(1, data, 0.0)

def AddData(builder, data):
    ActuatorCommandAddData(builder, data)

def ActuatorCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return ActuatorCommandEnd(builder)
