# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mujoco_data

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MujocoCommandFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MujocoCommandFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMujocoCommandFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MujocoCommandFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MujocoCommandFrame
    def Commands(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mujoco_data.ActuatorCommand import ActuatorCommand
            obj = ActuatorCommand()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MujocoCommandFrame
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MujocoCommandFrame
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def MujocoCommandFrameStart(builder):
    builder.StartObject(3)

def Start(builder):
    MujocoCommandFrameStart(builder)

def MujocoCommandFrameAddCommands(builder, commands):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(commands), 0)

def AddCommands(builder, commands):
    MujocoCommandFrameAddCommands(builder, commands)

def MujocoCommandFrameAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(1, timestamp, 0)

def AddTimestamp(builder, timestamp):
    MujocoCommandFrameAddTimestamp(builder, timestamp)

def MujocoCommandFrameAddFrameId(builder, frameId):
    builder.PrependUint64Slot(2, frameId, 0)

def AddFrameId(builder, frameId):
    MujocoCommandFrameAddFrameId(builder, frameId)

def MujocoCommandFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return MujocoCommandFrameEnd(builder)
