# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mujoco_data

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PoseData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PoseData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPoseData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PoseData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PoseData
    def BodyId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PoseData
    def BodyName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PoseData
    def BodyPos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # PoseData
    def BodyPosAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # PoseData
    def BodyPosLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PoseData
    def BodyPosIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # PoseData
    def BodyQuat(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # PoseData
    def BodyQuatAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # PoseData
    def BodyQuatLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PoseData
    def BodyQuatIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # PoseData
    def BodyVel(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # PoseData
    def BodyVelAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # PoseData
    def BodyVelLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PoseData
    def BodyVelIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def PoseDataStart(builder):
    builder.StartObject(5)

def Start(builder):
    PoseDataStart(builder)

def PoseDataAddBodyId(builder, bodyId):
    builder.PrependUint32Slot(0, bodyId, 0)

def AddBodyId(builder, bodyId):
    PoseDataAddBodyId(builder, bodyId)

def PoseDataAddBodyName(builder, bodyName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bodyName), 0)

def AddBodyName(builder, bodyName):
    PoseDataAddBodyName(builder, bodyName)

def PoseDataAddBodyPos(builder, bodyPos):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bodyPos), 0)

def AddBodyPos(builder, bodyPos):
    PoseDataAddBodyPos(builder, bodyPos)

def PoseDataStartBodyPosVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartBodyPosVector(builder, numElems):
    return PoseDataStartBodyPosVector(builder, numElems)

def PoseDataAddBodyQuat(builder, bodyQuat):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bodyQuat), 0)

def AddBodyQuat(builder, bodyQuat):
    PoseDataAddBodyQuat(builder, bodyQuat)

def PoseDataStartBodyQuatVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartBodyQuatVector(builder, numElems):
    return PoseDataStartBodyQuatVector(builder, numElems)

def PoseDataAddBodyVel(builder, bodyVel):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(bodyVel), 0)

def AddBodyVel(builder, bodyVel):
    PoseDataAddBodyVel(builder, bodyVel)

def PoseDataStartBodyVelVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartBodyVelVector(builder, numElems):
    return PoseDataStartBodyVelVector(builder, numElems)

def PoseDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return PoseDataEnd(builder)
