// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMANDFRAME_MUJOCO_DATA_H_
#define FLATBUFFERS_GENERATED_COMMANDFRAME_MUJOCO_DATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace mujoco_data {

struct ActuatorCommand;
struct ActuatorCommandBuilder;

struct MujocoCommandFrame;
struct MujocoCommandFrameBuilder;

struct ActuatorCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActuatorCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DATA = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  double data() const {
    return GetField<double>(VT_DATA, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<double>(verifier, VT_DATA, 8) &&
           verifier.EndTable();
  }
};

struct ActuatorCommandBuilder {
  typedef ActuatorCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(ActuatorCommand::VT_NAME, name);
  }
  void add_data(double data) {
    fbb_.AddElement<double>(ActuatorCommand::VT_DATA, data, 0.0);
  }
  explicit ActuatorCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ActuatorCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ActuatorCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ActuatorCommand> CreateActuatorCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    double data = 0.0) {
  ActuatorCommandBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ActuatorCommand> CreateActuatorCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    double data = 0.0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return mujoco_data::CreateActuatorCommand(
      _fbb,
      name__,
      data);
}

struct MujocoCommandFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MujocoCommandFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COMMANDS = 4,
    VT_TIMESTAMP = 6,
    VT_FRAME_ID = 8
  };
  const mujoco_data::ActuatorCommand *commands() const {
    return GetPointer<const mujoco_data::ActuatorCommand *>(VT_COMMANDS);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint64_t frame_id() const {
    return GetField<uint64_t>(VT_FRAME_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COMMANDS) &&
           verifier.VerifyTable(commands()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_FRAME_ID, 8) &&
           verifier.EndTable();
  }
};

struct MujocoCommandFrameBuilder {
  typedef MujocoCommandFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_commands(::flatbuffers::Offset<mujoco_data::ActuatorCommand> commands) {
    fbb_.AddOffset(MujocoCommandFrame::VT_COMMANDS, commands);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(MujocoCommandFrame::VT_TIMESTAMP, timestamp, 0);
  }
  void add_frame_id(uint64_t frame_id) {
    fbb_.AddElement<uint64_t>(MujocoCommandFrame::VT_FRAME_ID, frame_id, 0);
  }
  explicit MujocoCommandFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MujocoCommandFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MujocoCommandFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MujocoCommandFrame> CreateMujocoCommandFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<mujoco_data::ActuatorCommand> commands = 0,
    uint64_t timestamp = 0,
    uint64_t frame_id = 0) {
  MujocoCommandFrameBuilder builder_(_fbb);
  builder_.add_frame_id(frame_id);
  builder_.add_timestamp(timestamp);
  builder_.add_commands(commands);
  return builder_.Finish();
}

inline const mujoco_data::MujocoCommandFrame *GetMujocoCommandFrame(const void *buf) {
  return ::flatbuffers::GetRoot<mujoco_data::MujocoCommandFrame>(buf);
}

inline const mujoco_data::MujocoCommandFrame *GetSizePrefixedMujocoCommandFrame(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<mujoco_data::MujocoCommandFrame>(buf);
}

template <bool B = false>
inline bool VerifyMujocoCommandFrameBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<mujoco_data::MujocoCommandFrame>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMujocoCommandFrameBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<mujoco_data::MujocoCommandFrame>(nullptr);
}

inline void FinishMujocoCommandFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mujoco_data::MujocoCommandFrame> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMujocoCommandFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mujoco_data::MujocoCommandFrame> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace mujoco_data

#endif  // FLATBUFFERS_GENERATED_COMMANDFRAME_MUJOCO_DATA_H_
