// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMANDFRAME_MUJOCO_DATA_H_
#define FLATBUFFERS_GENERATED_COMMANDFRAME_MUJOCO_DATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace mujoco_data {

struct JointPosCommand;
struct JointPosCommandBuilder;

struct MujocoCommandFrame;
struct MujocoCommandFrameBuilder;

struct JointPosCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef JointPosCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_ID = 6,
    VT_POS = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const ::flatbuffers::Vector<double> *pos() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_POS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_POS) &&
           verifier.VerifyVector(pos()) &&
           verifier.EndTable();
  }
};

struct JointPosCommandBuilder {
  typedef JointPosCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(JointPosCommand::VT_NAME, name);
  }
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(JointPosCommand::VT_ID, id, 0);
  }
  void add_pos(::flatbuffers::Offset<::flatbuffers::Vector<double>> pos) {
    fbb_.AddOffset(JointPosCommand::VT_POS, pos);
  }
  explicit JointPosCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<JointPosCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<JointPosCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<JointPosCommand> CreateJointPosCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> pos = 0) {
  JointPosCommandBuilder builder_(_fbb);
  builder_.add_pos(pos);
  builder_.add_id(id);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<JointPosCommand> CreateJointPosCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t id = 0,
    const std::vector<double> *pos = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto pos__ = pos ? _fbb.CreateVector<double>(*pos) : 0;
  return mujoco_data::CreateJointPosCommand(
      _fbb,
      name__,
      id,
      pos__);
}

struct MujocoCommandFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MujocoCommandFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COMMANDS = 4,
    VT_TIMESTAMP = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<mujoco_data::JointPosCommand>> *commands() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mujoco_data::JointPosCommand>> *>(VT_COMMANDS);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COMMANDS) &&
           verifier.VerifyVector(commands()) &&
           verifier.VerifyVectorOfTables(commands()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct MujocoCommandFrameBuilder {
  typedef MujocoCommandFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_commands(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mujoco_data::JointPosCommand>>> commands) {
    fbb_.AddOffset(MujocoCommandFrame::VT_COMMANDS, commands);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(MujocoCommandFrame::VT_TIMESTAMP, timestamp, 0);
  }
  explicit MujocoCommandFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MujocoCommandFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MujocoCommandFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MujocoCommandFrame> CreateMujocoCommandFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mujoco_data::JointPosCommand>>> commands = 0,
    uint64_t timestamp = 0) {
  MujocoCommandFrameBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_commands(commands);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MujocoCommandFrame> CreateMujocoCommandFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<mujoco_data::JointPosCommand>> *commands = nullptr,
    uint64_t timestamp = 0) {
  auto commands__ = commands ? _fbb.CreateVector<::flatbuffers::Offset<mujoco_data::JointPosCommand>>(*commands) : 0;
  return mujoco_data::CreateMujocoCommandFrame(
      _fbb,
      commands__,
      timestamp);
}

inline const mujoco_data::MujocoCommandFrame *GetMujocoCommandFrame(const void *buf) {
  return ::flatbuffers::GetRoot<mujoco_data::MujocoCommandFrame>(buf);
}

inline const mujoco_data::MujocoCommandFrame *GetSizePrefixedMujocoCommandFrame(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<mujoco_data::MujocoCommandFrame>(buf);
}

template <bool B = false>
inline bool VerifyMujocoCommandFrameBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<mujoco_data::MujocoCommandFrame>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMujocoCommandFrameBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<mujoco_data::MujocoCommandFrame>(nullptr);
}

inline void FinishMujocoCommandFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mujoco_data::MujocoCommandFrame> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMujocoCommandFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mujoco_data::MujocoCommandFrame> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace mujoco_data

#endif  // FLATBUFFERS_GENERATED_COMMANDFRAME_MUJOCO_DATA_H_
