// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATAFRAME_MUJOCO_SHM_H_
#define FLATBUFFERS_GENERATED_DATAFRAME_MUJOCO_SHM_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace mujoco_shm {

struct SensorData;
struct SensorDataBuilder;

struct JointData;
struct JointDataBuilder;

struct PoseData;
struct PoseDataBuilder;

struct MujocoDataFrame;
struct MujocoDataFrameBuilder;

enum JointType : uint8_t {
  JointType_FORCE = 0,
  JointType_IMU = 1,
  JointType_ENCODER = 2,
  JointType_MIN = JointType_FORCE,
  JointType_MAX = JointType_ENCODER
};

inline const JointType (&EnumValuesJointType())[3] {
  static const JointType values[] = {
    JointType_FORCE,
    JointType_IMU,
    JointType_ENCODER
  };
  return values;
}

inline const char * const *EnumNamesJointType() {
  static const char * const names[4] = {
    "FORCE",
    "IMU",
    "ENCODER",
    nullptr
  };
  return names;
}

inline const char *EnumNameJointType(JointType e) {
  if (::flatbuffers::IsOutRange(e, JointType_FORCE, JointType_ENCODER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesJointType()[index];
}

struct SensorData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SensorDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SENSOR_ID = 4,
    VT_VALUES = 6,
    VT_NAME = 8
  };
  uint32_t sensor_id() const {
    return GetField<uint32_t>(VT_SENSOR_ID, 0);
  }
  const ::flatbuffers::Vector<double> *values() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_VALUES);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SENSOR_ID, 4) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct SensorDataBuilder {
  typedef SensorData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sensor_id(uint32_t sensor_id) {
    fbb_.AddElement<uint32_t>(SensorData::VT_SENSOR_ID, sensor_id, 0);
  }
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<double>> values) {
    fbb_.AddOffset(SensorData::VT_VALUES, values);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SensorData::VT_NAME, name);
  }
  explicit SensorDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SensorData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SensorData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SensorData> CreateSensorData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sensor_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> values = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  SensorDataBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_values(values);
  builder_.add_sensor_id(sensor_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SensorData> CreateSensorDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sensor_id = 0,
    const std::vector<double> *values = nullptr,
    const char *name = nullptr) {
  auto values__ = values ? _fbb.CreateVector<double>(*values) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return mujoco_shm::CreateSensorData(
      _fbb,
      sensor_id,
      values__,
      name__);
}

struct JointData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef JointDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_JOINT_ID = 4,
    VT_NAME = 6,
    VT_QPOS = 8,
    VT_QVEL = 10
  };
  uint32_t joint_id() const {
    return GetField<uint32_t>(VT_JOINT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  double qpos() const {
    return GetField<double>(VT_QPOS, 0.0);
  }
  double qvel() const {
    return GetField<double>(VT_QVEL, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_JOINT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<double>(verifier, VT_QPOS, 8) &&
           VerifyField<double>(verifier, VT_QVEL, 8) &&
           verifier.EndTable();
  }
};

struct JointDataBuilder {
  typedef JointData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_joint_id(uint32_t joint_id) {
    fbb_.AddElement<uint32_t>(JointData::VT_JOINT_ID, joint_id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(JointData::VT_NAME, name);
  }
  void add_qpos(double qpos) {
    fbb_.AddElement<double>(JointData::VT_QPOS, qpos, 0.0);
  }
  void add_qvel(double qvel) {
    fbb_.AddElement<double>(JointData::VT_QVEL, qvel, 0.0);
  }
  explicit JointDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<JointData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<JointData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<JointData> CreateJointData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t joint_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    double qpos = 0.0,
    double qvel = 0.0) {
  JointDataBuilder builder_(_fbb);
  builder_.add_qvel(qvel);
  builder_.add_qpos(qpos);
  builder_.add_name(name);
  builder_.add_joint_id(joint_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<JointData> CreateJointDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t joint_id = 0,
    const char *name = nullptr,
    double qpos = 0.0,
    double qvel = 0.0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return mujoco_shm::CreateJointData(
      _fbb,
      joint_id,
      name__,
      qpos,
      qvel);
}

struct PoseData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PoseDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_ID = 4,
    VT_BODY_NAME = 6,
    VT_BODY_POS = 8,
    VT_BODY_QUAT = 10,
    VT_BODY_VEL = 12
  };
  uint32_t body_id() const {
    return GetField<uint32_t>(VT_BODY_ID, 0);
  }
  const ::flatbuffers::String *body_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY_NAME);
  }
  const ::flatbuffers::Vector<double> *body_pos() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_BODY_POS);
  }
  const ::flatbuffers::Vector<double> *body_quat() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_BODY_QUAT);
  }
  const ::flatbuffers::Vector<double> *body_vel() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_BODY_VEL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_BODY_ID, 4) &&
           VerifyOffset(verifier, VT_BODY_NAME) &&
           verifier.VerifyString(body_name()) &&
           VerifyOffset(verifier, VT_BODY_POS) &&
           verifier.VerifyVector(body_pos()) &&
           VerifyOffset(verifier, VT_BODY_QUAT) &&
           verifier.VerifyVector(body_quat()) &&
           VerifyOffset(verifier, VT_BODY_VEL) &&
           verifier.VerifyVector(body_vel()) &&
           verifier.EndTable();
  }
};

struct PoseDataBuilder {
  typedef PoseData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_id(uint32_t body_id) {
    fbb_.AddElement<uint32_t>(PoseData::VT_BODY_ID, body_id, 0);
  }
  void add_body_name(::flatbuffers::Offset<::flatbuffers::String> body_name) {
    fbb_.AddOffset(PoseData::VT_BODY_NAME, body_name);
  }
  void add_body_pos(::flatbuffers::Offset<::flatbuffers::Vector<double>> body_pos) {
    fbb_.AddOffset(PoseData::VT_BODY_POS, body_pos);
  }
  void add_body_quat(::flatbuffers::Offset<::flatbuffers::Vector<double>> body_quat) {
    fbb_.AddOffset(PoseData::VT_BODY_QUAT, body_quat);
  }
  void add_body_vel(::flatbuffers::Offset<::flatbuffers::Vector<double>> body_vel) {
    fbb_.AddOffset(PoseData::VT_BODY_VEL, body_vel);
  }
  explicit PoseDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PoseData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PoseData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PoseData> CreatePoseData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t body_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> body_name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> body_pos = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> body_quat = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> body_vel = 0) {
  PoseDataBuilder builder_(_fbb);
  builder_.add_body_vel(body_vel);
  builder_.add_body_quat(body_quat);
  builder_.add_body_pos(body_pos);
  builder_.add_body_name(body_name);
  builder_.add_body_id(body_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PoseData> CreatePoseDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t body_id = 0,
    const char *body_name = nullptr,
    const std::vector<double> *body_pos = nullptr,
    const std::vector<double> *body_quat = nullptr,
    const std::vector<double> *body_vel = nullptr) {
  auto body_name__ = body_name ? _fbb.CreateString(body_name) : 0;
  auto body_pos__ = body_pos ? _fbb.CreateVector<double>(*body_pos) : 0;
  auto body_quat__ = body_quat ? _fbb.CreateVector<double>(*body_quat) : 0;
  auto body_vel__ = body_vel ? _fbb.CreateVector<double>(*body_vel) : 0;
  return mujoco_shm::CreatePoseData(
      _fbb,
      body_id,
      body_name__,
      body_pos__,
      body_quat__,
      body_vel__);
}

struct MujocoDataFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MujocoDataFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DESCRIPTION = 4,
    VT_TIMESTAMP = 6,
    VT_FRAME_ID = 8,
    VT_SIM_TIME = 10,
    VT_JOINTS = 12,
    VT_SENSORS = 14,
    VT_BODIES = 16,
    VT_IS_VALID = 18
  };
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint64_t frame_id() const {
    return GetField<uint64_t>(VT_FRAME_ID, 0);
  }
  double sim_time() const {
    return GetField<double>(VT_SIM_TIME, 0.0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::JointData>> *joints() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::JointData>> *>(VT_JOINTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::SensorData>> *sensors() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::SensorData>> *>(VT_SENSORS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::PoseData>> *bodies() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::PoseData>> *>(VT_BODIES);
  }
  bool is_valid() const {
    return GetField<uint8_t>(VT_IS_VALID, 1) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_FRAME_ID, 8) &&
           VerifyField<double>(verifier, VT_SIM_TIME, 8) &&
           VerifyOffset(verifier, VT_JOINTS) &&
           verifier.VerifyVector(joints()) &&
           verifier.VerifyVectorOfTables(joints()) &&
           VerifyOffset(verifier, VT_SENSORS) &&
           verifier.VerifyVector(sensors()) &&
           verifier.VerifyVectorOfTables(sensors()) &&
           VerifyOffset(verifier, VT_BODIES) &&
           verifier.VerifyVector(bodies()) &&
           verifier.VerifyVectorOfTables(bodies()) &&
           VerifyField<uint8_t>(verifier, VT_IS_VALID, 1) &&
           verifier.EndTable();
  }
};

struct MujocoDataFrameBuilder {
  typedef MujocoDataFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(MujocoDataFrame::VT_DESCRIPTION, description);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(MujocoDataFrame::VT_TIMESTAMP, timestamp, 0);
  }
  void add_frame_id(uint64_t frame_id) {
    fbb_.AddElement<uint64_t>(MujocoDataFrame::VT_FRAME_ID, frame_id, 0);
  }
  void add_sim_time(double sim_time) {
    fbb_.AddElement<double>(MujocoDataFrame::VT_SIM_TIME, sim_time, 0.0);
  }
  void add_joints(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::JointData>>> joints) {
    fbb_.AddOffset(MujocoDataFrame::VT_JOINTS, joints);
  }
  void add_sensors(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::SensorData>>> sensors) {
    fbb_.AddOffset(MujocoDataFrame::VT_SENSORS, sensors);
  }
  void add_bodies(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::PoseData>>> bodies) {
    fbb_.AddOffset(MujocoDataFrame::VT_BODIES, bodies);
  }
  void add_is_valid(bool is_valid) {
    fbb_.AddElement<uint8_t>(MujocoDataFrame::VT_IS_VALID, static_cast<uint8_t>(is_valid), 1);
  }
  explicit MujocoDataFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MujocoDataFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MujocoDataFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MujocoDataFrame> CreateMujocoDataFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    uint64_t timestamp = 0,
    uint64_t frame_id = 0,
    double sim_time = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::JointData>>> joints = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::SensorData>>> sensors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mujoco_shm::PoseData>>> bodies = 0,
    bool is_valid = true) {
  MujocoDataFrameBuilder builder_(_fbb);
  builder_.add_sim_time(sim_time);
  builder_.add_frame_id(frame_id);
  builder_.add_timestamp(timestamp);
  builder_.add_bodies(bodies);
  builder_.add_sensors(sensors);
  builder_.add_joints(joints);
  builder_.add_description(description);
  builder_.add_is_valid(is_valid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MujocoDataFrame> CreateMujocoDataFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *description = nullptr,
    uint64_t timestamp = 0,
    uint64_t frame_id = 0,
    double sim_time = 0.0,
    const std::vector<::flatbuffers::Offset<mujoco_shm::JointData>> *joints = nullptr,
    const std::vector<::flatbuffers::Offset<mujoco_shm::SensorData>> *sensors = nullptr,
    const std::vector<::flatbuffers::Offset<mujoco_shm::PoseData>> *bodies = nullptr,
    bool is_valid = true) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto joints__ = joints ? _fbb.CreateVector<::flatbuffers::Offset<mujoco_shm::JointData>>(*joints) : 0;
  auto sensors__ = sensors ? _fbb.CreateVector<::flatbuffers::Offset<mujoco_shm::SensorData>>(*sensors) : 0;
  auto bodies__ = bodies ? _fbb.CreateVector<::flatbuffers::Offset<mujoco_shm::PoseData>>(*bodies) : 0;
  return mujoco_shm::CreateMujocoDataFrame(
      _fbb,
      description__,
      timestamp,
      frame_id,
      sim_time,
      joints__,
      sensors__,
      bodies__,
      is_valid);
}

inline const mujoco_shm::MujocoDataFrame *GetMujocoDataFrame(const void *buf) {
  return ::flatbuffers::GetRoot<mujoco_shm::MujocoDataFrame>(buf);
}

inline const mujoco_shm::MujocoDataFrame *GetSizePrefixedMujocoDataFrame(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<mujoco_shm::MujocoDataFrame>(buf);
}

template <bool B = false>
inline bool VerifyMujocoDataFrameBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<mujoco_shm::MujocoDataFrame>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMujocoDataFrameBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<mujoco_shm::MujocoDataFrame>(nullptr);
}

inline void FinishMujocoDataFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mujoco_shm::MujocoDataFrame> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMujocoDataFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mujoco_shm::MujocoDataFrame> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace mujoco_shm

#endif  // FLATBUFFERS_GENERATED_DATAFRAME_MUJOCO_SHM_H_
